//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demik3
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        public int Id { get; set; }
        public int knifeId { get; set; }
        public int clientId { get; set; }
        public int colorId { get; set; }
    
        public virtual client client { get; set; }
        public virtual color color { get; set; }
    }
}
